### ISSUE TITLE
Unit tests failed for adjoint sparse Hamiltonian method

### ISSUE THREAD

**Issue by multiphaseCFD** [PennyLaneAI/pennylane-lightning-gpu#129]
#### Issue description

Currently, the unit test for adjoint sparse Hamiltonian fails if `PauliY` is replaced `PauliZ` in the [line](https://github.com/PennyLaneAI/pennylane-lightning-gpu/blob/37a5e0378729499814897d8e104d31a988ba973f/tests/test_adjoint_jacobian.py#L1085).
The reason why it fails might be because the wires order of sparse matrix in adjoint sparse Hamiltonian is not reversed as other gate ops does. If it's true, we might be able to fix it with the method mentioned in PR#129.

**Comment by vincentmr** [comment]
What is the branch/commit? Runtime config (i.e. how many GPUs)?

**Comment by vincentmr** [comment]
I modified the test to take in various coefficients, the same combinations of `custom_wires` indices, and run over all combinations of Pauli matrices, and everything passes.
```
@pytest.mark.parametrize("coeff", 4.0 * (np.random.rand(100) - 0.5))
@pytest.mark.parametrize("indices", [[0, 1], [2, 0], [0, 2]])
@pytest.mark.parametrize("obs0", [qml.PauliX, qml.PauliY, qml.PauliZ])
@pytest.mark.parametrize("obs1", [qml.PauliX, qml.PauliY, qml.PauliZ])
def test_adjoint_SparseHamiltonian(coeff, indices, obs0, obs1):
    """Integration tests that compare to default.qubit for a large circuit containing parametrized
    operations and when using custom wire labels"""

    dev_gpu = qml.device("lightning.gpu", wires=custom_wires)
    dev_cpu = qml.device("default.qubit", wires=custom_wires)

    returns = qml.SparseHamiltonian(
        qml.Hamiltonian(
            [coeff], [obs0(wires=custom_wires[indices[0]]) @ obs1(wires=custom_wires[indices[1]])]
        ).sparse_matrix(custom_wires),
        wires=custom_wires,
    )

    def circuit(params):
        circuit_ansatz(params, wires=custom_wires)
        return qml.expval(returns)

    n_params = 30
    np.random.seed(1337)
    params = np.random.rand(n_params)

    qnode_gpu = qml.QNode(circuit, dev_gpu, diff_method="adjoint")
    qnode_cpu = qml.QNode(circuit, dev_cpu, diff_method="parameter-shift")

    j_gpu = qml.jacobian(qnode_gpu)(params)
    j_cpu = qml.jacobian(qnode_cpu)(params)

    assert np.allclose(j_cpu, j_gpu)
```

**Comment by multiphaseCFD** [comment]
hmmm, just rerun your script and failed again. We might need a discussion on this. @vincentmr

**Comment by multiphaseCFD** [comment]
> What is the branch/commit? Runtime config (i.e. how many GPUs)?

One GPU only on Perlmutter.
