### ISSUE TITLE
Pushing current updates to PyPi

### ISSUE THREAD

**Issue by dominicpasquali** [PennyLaneAI/pennylane-lightning-gpu#14]
#### Issue description

Requesting that this updated repo be pushed to PyPi (https://pypi.org/project/PennyLane-Lightning-GPU/). Current changes in this repo since the last push to PyPi are significant.

**Comment by mlxd** [comment]
Hi @dominicpasquali PennyLane packages tend to follow a given release cycle, as we develop changes together across several packages in the ecosystem at the same time. The current changes in main here will be synchronized against https://github.com/PennyLaneAI/pennylane and https://github.com/PennyLaneAI/pennylane-lightning main/master branches. We anticipate the next release to come out for all packages in a few weeks.

Though, if you require access to wheels of the latest binary, the [builder instructions](https://github.com/PennyLaneAI/pennylane-lightning-gpu#build-locally-with-docker) can be run locally using docker, and will give you immediate access. You should also install the latest versions of PennyLane and Lightning packages with this, as package versions 0.22.x will be incompatible with the coming changes for 0.23.x

**Comment by mlxd** [comment]
Feel free to reach out if you need further assistance.

**Comment by dominicpasquali** [comment]
Good to know and will do. Thanks!
