### ISSUE TITLE
GPU implementations samples

### ISSUE THREAD

**Issue by nithingovindugari** [PennyLaneAI/pennylane-lightning-gpu#146]
I recently attempted to test the PennyLane-Lightning-GPU feature. Given that I don't currently have access to a local GPU setup, I opted to use Google Colab for this purpose. However, I encountered challenges in fully utilizing the GPU capabilities within the Colab environment as It goes back to using cpu instead of gpu with attached warning. Additionally, I found that the documentation for PennyLane-Lightning-GPU, in contrast to the more straightforward guidance provided for traditional PennyLane, wasn't as clear or detailed as I had hoped.

To better understand and effectively use PennyLane-Lightning-GPU, I am looking for sample notebooks or practical examples that demonstrate its implementation. Such resources would be incredibly helpful in navigating the setup process and in exploring the capabilities of PennyLane-Lightning-GPU, especially in a cloud-based environment like Google Colab. Any pointers or references to such materials would be greatly appreciated.
<img width="1441" alt="image" src="https://github.com/PennyLaneAI/pennylane-lightning-gpu/assets/42509742/55aa48e3-e0e8-4c1a-ada0-e9f5b89aa993">

**Comment by isaacdevlugt** [comment]
Hey @nithingovindugari! Can you try this with cuquantum-cu11 or with custatevec-cu11? Lightning GPU does not currently support CUDA 12.

**Comment by nithingovindugari** [comment]
Hi , I am facing the same with custatevec-cu11 as well and I tracked my gpu usage status and its not utilizing any gpu. I wonder if you could share links to any open source sample notebooks or code implemented utilizing gpu's it would help to keep it as reference.

<img width="1459" alt="image" src="https://github.com/PennyLaneAI/pennylane-lightning-gpu/assets/42509742/b8cf2142-c44d-4161-8039-16525b4fef43">

**Comment by isaacdevlugt** [comment]
Ah! I think you need to install these:

```
pip install nvidia-cusparse-cu11 nvidia-cublas-cu11 nvidia-cuda-runtime-cu11 custatevec_cu11
```

Indeed, this isn't very clear in the README. One of our devs will update this soon. Let me know if this fixes it!

**Comment by nithingovindugari** [comment]
Thank you am about to post the same..I tried installing mentioned libraries morning and it worked am closing the issue and thank you
